project:
  type: website

website:
  title: "mamiecincotta.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - teaching.qmd
      - personal.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


