---
title: "EPPS 6302 Assignments"
editor: visual
---

# Assignment One

[Link to survey](https://utdallas.qualtrics.com/jfe/form/SV_aavYATLIL7LFra6)

Analysis:

a\. The survey is structured with an introduction first,

b\. The questionnaire is composed of questions about levels of agreement/disagreemnet with given statements, purchasing habits, willingness to buy certain theoretical products and what the pricing should be, and demographic information.

c\. The questions are ordered with the agreement/disagreement assessments being placed first, questions about purchasing habits coming after, and demographic information being placed last.

Improvements:

I think the page breaks could be placed in a way to keep related questions grouped together on the same page. This would improve user experience by allowing the respondent to view their responses to related questions.

# Assignment Two

c\. The Google Trends website is more visually appealing to me then RStudio, but I found it a little bit more confusing to see how to download the data on the website than with RStudio. I enjoy that RStudio gives me more tools to graph the data on my own than the website, but I'm not proficient enough in RStudio yet to create graphs that show shading based on the states.

# Assignment 3

3a. The Biden-Xi summit data shows that a lot of the conversations revolved around human rights abuses by China (specifically against Uyghurs). Additional topics included Coronavirus and Fentanyl.

3b. In the inaugural speeches, the differences in the focuses of presidents is interesting. Each president has their own different focuses, but they also share some commonalities. While "generations", "friends", and "families" for Obama, Bush, and Trump may all be different words, they all indicate a focus on the people of the nation. Additionally, all of the innagural speeches seem to focus at least partial on american values like liberty and freedom. Certain presidents, like Trump, also include specific policy areas in their speeches. Trump talks about the border a lot. This is due to how much his campaign was centered around borders and immigration issues. In the past, presidents were also much more likely to mention certain terms like communist. For the frequency of the word "American", it was surprising to me that Clinton and then Trump most frequently used the word. The differences between the use of the word "must" was also interesting, with it appearing on the charts for both Obama and Biden (democrats) but not on the charts for Bush and Trump (Republicans).

4.  Wordfish is a computer program that takes the frequency of words in certain documents and then is able to give where that document would be on a one-dimensional scale of what it's political position is.

# Assignment 4

3a. With the wikipedia data, I think the dataframe that results is fairly usable\> However, there are some problems with the labeling of the table. The table has labels that I personally do not think best convey the information in the column and the first row of data is not actually data and is instead another set of column labels.

3b. The process of scraping government data was longer and more complex that scraping wikipedia table data. This is partially because of the fact that Wikipedia data is just on a single webpage while the government document data requires naviagting a government search webpage. I think one of the important parts of downloading government document data is planning what you would like to download initially. Because of the amount of time taken to download documents, especially in bulk, being aware of what specifically you want to download is important. Additionally, for the wikipedia data, it would be useful to change the code so that the column names make a bit more sense when they're downloaded.

# Assignment 5

3.  Yes! It is possible to use quanteda to analyze the content of the YouTube comments.
